--
- name: install apache server on redhat
  hosts: website
  become: yes
  tasks:
    - name: install apache server on redhat
      ansible.builtin.dnf:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"
    - name: ensure apache service is running
      ansible.builtin.systemd_service:
        name: httpd
        enabled: yes
        state: started
      when: ansible_facts['os_family'] == "RedHat"
    - name: install apache server on ubuntu 
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: ensure apache service is running 
      ansible.builtin.systemd_service:
        name: apache2
        enabled: yes
        state: started
      when: ansible_facts['os_family'] == "Debian"