---
- name: Deploying a website
  become: yes
  hosts: all
  tasks:
    - name: Install nginx and unzip
      ansible.builtin.apt:
        name:
          - nginx
          - unzip
        update_cache: true
        state: present

    - name: Installing website
      ansible.builtin.get_url:
        url: https://www.free-css.com/assets/files/free-css-templates/download/page295/antique-cafe.zip
        dest: /tmp/antique-cafe.zip

    - name: Unzip website
      ansible.builtin.unarchive:
        remote_src: true
        src: /tmp/antique-cafe.zip
        dest: /tmp/antique-cafe/

    - name: Move website to the correct directory
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/antique-cafe/
        dest: /var/www/html/cafe
